# Generated by Django 6.0.6 on 2026-06-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0003_lead_company_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
            preserve_default=False,
        ),
    ]
