# Generated by Django 6.0.6 on 2026-07-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0002_contact_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
