# Generated by Django 6.0.6 on 2026-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
