# Generated by Django 6.0.6 on 2026-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_source_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
